// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Joy.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_JOY_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_JOY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "std_msgs/msg/Header.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(JOY_SOURCE)
#define JOY_DllAPI __declspec( dllexport )
#else
#define JOY_DllAPI __declspec( dllimport )
#endif // JOY_SOURCE
#else
#define JOY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define JOY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace sensor_msgs {

namespace msg {





/*!
 * @brief This class represents the structure Joy defined by the user in the IDL file.
 * @ingroup Joy
 */
class Joy
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Joy();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Joy();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    eProsima_user_DllExport Joy(
            const Joy& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    eProsima_user_DllExport Joy(
            Joy&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    eProsima_user_DllExport Joy& operator =(
            const Joy& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object sensor_msgs::msg::Joy that will be copied.
     */
    eProsima_user_DllExport Joy& operator =(
            Joy&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::Joy object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Joy& x) const;

    /*!
     * @brief Comparison operator.
     * @param x sensor_msgs::msg::Joy object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Joy& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::Header& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::Header&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::Header& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::Header& header();


    /*!
     * @brief This function copies the value in member axes
     * @param _axes New value to be copied in member axes
     */
    eProsima_user_DllExport void axes(
            const std::vector<float>& _axes);

    /*!
     * @brief This function moves the value in member axes
     * @param _axes New value to be moved in member axes
     */
    eProsima_user_DllExport void axes(
            std::vector<float>&& _axes);

    /*!
     * @brief This function returns a constant reference to member axes
     * @return Constant reference to member axes
     */
    eProsima_user_DllExport const std::vector<float>& axes() const;

    /*!
     * @brief This function returns a reference to member axes
     * @return Reference to member axes
     */
    eProsima_user_DllExport std::vector<float>& axes();


    /*!
     * @brief This function copies the value in member buttons
     * @param _buttons New value to be copied in member buttons
     */
    eProsima_user_DllExport void buttons(
            const std::vector<int32_t>& _buttons);

    /*!
     * @brief This function moves the value in member buttons
     * @param _buttons New value to be moved in member buttons
     */
    eProsima_user_DllExport void buttons(
            std::vector<int32_t>&& _buttons);

    /*!
     * @brief This function returns a constant reference to member buttons
     * @return Constant reference to member buttons
     */
    eProsima_user_DllExport const std::vector<int32_t>& buttons() const;

    /*!
     * @brief This function returns a reference to member buttons
     * @return Reference to member buttons
     */
    eProsima_user_DllExport std::vector<int32_t>& buttons();

private:

    std_msgs::msg::Header m_header;
    std::vector<float> m_axes;
    std::vector<int32_t> m_buttons;

};

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_JOY_H_



